kind: Secret
apiVersion: v1
metadata:
  name: demo-podinfo-registry-creds
  namespace: demo-podinfo
immutable: false
data:
  config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LXNnNndzLmFwcHMuY2x1c3Rlci1zZzZ3cy5zZzZ3cy5zYW5kYm94MTM5OS5vcGVudGxjLmNvbSI6IHsKICAgICAgImF1dGgiOiAieW91ciByZXBvc2l0b3J5IHRva2VuIGhlcmUiCiAgICB9CiAgfQp9Cgo=
type: Opaque
